// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterarFoto(arg1) {
  return window['go']['main']['App']['AlterarFoto'](arg1);
}

export function AlterarSenha(arg1, arg2) {
  return window['go']['main']['App']['AlterarSenha'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AtivarPaymentGateway(arg1, arg2) {
  return window['go']['main']['App']['AtivarPaymentGateway'](arg1, arg2);
}

export function AtivarPaymentMethod(arg1, arg2) {
  return window['go']['main']['App']['AtivarPaymentMethod'](arg1, arg2);
}

export function AtivarPlano(arg1, arg2) {
  return window['go']['main']['App']['AtivarPlano'](arg1, arg2);
}

export function AtivarStudent(arg1, arg2) {
  return window['go']['main']['App']['AtivarStudent'](arg1, arg2);
}

export function AtivarUsuario(arg1, arg2) {
  return window['go']['main']['App']['AtivarUsuario'](arg1, arg2);
}

export function AtualizarConfigGateway(arg1, arg2) {
  return window['go']['main']['App']['AtualizarConfigGateway'](arg1, arg2);
}

export function AtualizarPlano(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AtualizarPlano'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AtualizarPlanoAluno(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AtualizarPlanoAluno'](arg1, arg2, arg3, arg4);
}

export function AtualizarStudent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AtualizarStudent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AtualizarUsuario(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AtualizarUsuario'](arg1, arg2, arg3, arg4);
}

export function BuscarInvoice(arg1) {
  return window['go']['main']['App']['BuscarInvoice'](arg1);
}

export function BuscarPlano(arg1) {
  return window['go']['main']['App']['BuscarPlano'](arg1);
}

export function BuscarStudent(arg1) {
  return window['go']['main']['App']['BuscarStudent'](arg1);
}

export function BuscarStudentPlan(arg1) {
  return window['go']['main']['App']['BuscarStudentPlan'](arg1);
}

export function BuscarUsuario(arg1) {
  return window['go']['main']['App']['BuscarUsuario'](arg1);
}

export function CadastrarAluno(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CadastrarAluno'](arg1, arg2, arg3, arg4);
}

export function CancelarInvoice(arg1) {
  return window['go']['main']['App']['CancelarInvoice'](arg1);
}

export function CancelarStudentPlan(arg1) {
  return window['go']['main']['App']['CancelarStudentPlan'](arg1);
}

export function ConfirmarPagamento(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmarPagamento'](arg1, arg2, arg3);
}

export function CriarInvoiceTeste() {
  return window['go']['main']['App']['CriarInvoiceTeste']();
}

export function CriarPaymentMethod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CriarPaymentMethod'](arg1, arg2, arg3, arg4);
}

export function CriarPlano(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CriarPlano'](arg1, arg2, arg3, arg4, arg5);
}

export function CriarStudent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CriarStudent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CriarStudentComPlano(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CriarStudentComPlano'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CriarStudentPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['CriarStudentPlan'](arg1, arg2, arg3);
}

export function CriarUsuario(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CriarUsuario'](arg1, arg2, arg3, arg4, arg5);
}

export function DeletarDadosTeste() {
  return window['go']['main']['App']['DeletarDadosTeste']();
}

export function DeletarInvoice(arg1) {
  return window['go']['main']['App']['DeletarInvoice'](arg1);
}

export function DeletarPlano(arg1) {
  return window['go']['main']['App']['DeletarPlano'](arg1);
}

export function DeletarUsuario(arg1) {
  return window['go']['main']['App']['DeletarUsuario'](arg1);
}

export function GerarInvoice(arg1) {
  return window['go']['main']['App']['GerarInvoice'](arg1);
}

export function ListarAccessLogs() {
  return window['go']['main']['App']['ListarAccessLogs']();
}

export function ListarAlunosPorPlano(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListarAlunosPorPlano'](arg1, arg2, arg3);
}

export function ListarAuditLogs() {
  return window['go']['main']['App']['ListarAuditLogs']();
}

export function ListarCobranca() {
  return window['go']['main']['App']['ListarCobranca']();
}

export function ListarInadimplentes() {
  return window['go']['main']['App']['ListarInadimplentes']();
}

export function ListarInvoices() {
  return window['go']['main']['App']['ListarInvoices']();
}

export function ListarPaymentGateways() {
  return window['go']['main']['App']['ListarPaymentGateways']();
}

export function ListarPaymentMethods() {
  return window['go']['main']['App']['ListarPaymentMethods']();
}

export function ListarPlanos() {
  return window['go']['main']['App']['ListarPlanos']();
}

export function ListarStudentPlans() {
  return window['go']['main']['App']['ListarStudentPlans']();
}

export function ListarStudents() {
  return window['go']['main']['App']['ListarStudents']();
}

export function ListarStudentsComPlanos() {
  return window['go']['main']['App']['ListarStudentsComPlanos']();
}

export function ListarUsuarios() {
  return window['go']['main']['App']['ListarUsuarios']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MeuPerfil() {
  return window['go']['main']['App']['MeuPerfil']();
}

export function ObterEstatisticasAcesso(arg1) {
  return window['go']['main']['App']['ObterEstatisticasAcesso'](arg1);
}

export function ObterMetricasHome() {
  return window['go']['main']['App']['ObterMetricasHome']();
}

export function SalvarComprovante(arg1, arg2, arg3) {
  return window['go']['main']['App']['SalvarComprovante'](arg1, arg2, arg3);
}

export function SalvarPermissoesUsuario(arg1, arg2) {
  return window['go']['main']['App']['SalvarPermissoesUsuario'](arg1, arg2);
}

export function VerificarAcessoAluno(arg1) {
  return window['go']['main']['App']['VerificarAcessoAluno'](arg1);
}
